data = {'Arial': 'Arial.ttf',
        'Arial Italic': 'Ariali.ttf',
        'Arial Bold': 'Arialbd.ttf',
        'Arial Bold Italic': 'Arialbi.ttf',
        'Arial Black': 'Ariblk.ttf',
        'Calibri Light': 'Calibril.ttf',
        'Calibri Light Italic': 'Calibrili.ttf',
        'Calibri': 'Calibri.ttf',
        'Calibri Italic': 'Calibrii.ttf',
        'Calibri Bold': 'Calibrib.ttf',
        'Calibri Bold Italic': 'Calibriz.ttf',
        'Cambria Italic': 'Cambriai.ttf',
        'Cambria Bold': 'Cambriab.ttf',
        'Candara': 'Candara.ttf',
        'Candara Italic': 'Candarai.ttf',
        'Candara Bold': 'Candarab.ttf',
        'Candara Bold Italic': 'Candaraz.ttf',
        'Comic Sans MS': 'Comic.ttf',
        'Comic Sans MS Italic': 'Comici.ttf',
        'Comic Sans MS Bold': 'Comicbd.ttf',
        'Comic Sans MS Bold Italic': 'Comicz.ttf',
        'Consolas': 'Consola.ttf',
        'Consolas Italic': 'Consolai.ttf',
        'Consolas Bold': 'Consolab.ttf',
        'Consolas Bold Italic': 'Consolaz.ttf',
        'Constantia': 'Constan.ttf',
        'Constantia Italic': 'Constani.ttf',
        'Constantia Bold': 'Constanb.ttf',
        'Constantia Bold Italic': 'Constanz.ttf',
        'Corbel': 'Corbel.ttf',
        'Corbel Italic': 'Corbeli.ttf',
        'Corbel Bold': 'Corbelb.ttf',
        'Corbel Bold Italic': 'Corbelz.ttf',
        'Courier New': 'Cour.ttf',
        'Courier New Italic': 'Couri.ttf',
        'Courier New Bold': 'Courbd.ttf',
        'Courier New Bold Italic': 'Courbi.ttf',
        'Ebrima': 'Ebrima.ttf',
        'Ebrima Bold': 'Ebrimabd.ttf',
        'Franklin Gothic Medium': 'Framd.ttf',
        'Franklin Gothic Medium Italic': 'Framdit.ttf',
        'Gabriola': 'Gabriola.ttf',
        'Gadugi': 'Gadugi.ttf',
        'Gadugi Bold': 'Gadugib.ttf',
        'Georgia': 'Georgia.ttf',
        'Georgia Italic': 'Georgiai.ttf',
        'Georgia Bold': 'Georgiab.ttf',
        'Georgia Bold Italic': 'Georgiaz.ttf',
        'Impact': 'Impact.ttf',
        'Javanese Text': 'Javatext.ttf',
        'Leelawadee UI': 'Leelawui.ttf',
        'Leelawadee UI Semilight': 'Leeluisl.ttf',
        'Leelawadee UI Bold': 'Leelauib.ttf',
        'Lucida Console': 'Lucon.ttf',
        'Lucida Sans Unicode': 'L_10646.ttf',
        'Malgun Gothic': 'Malgun.ttf',
        'Malgun Gothic Bold': 'Malgunbd.ttf',
        'Microsoft New Tai Lue': 'Ntailu.ttf',
        'Microsoft New Tai Lue Bold': 'Ntailub.ttf',
        'Microsoft Tai Le': 'Taile.ttf',
        'Microsoft Yi Baiti': 'Msyi.ttf',
        'Mongolian Baiti': 'Monbaiti.ttf',
        'MV Boli': 'Mvboli.ttf',
        'Myanmar Text': 'Mmrtext.ttf',
        'Myanmar Text Bold': 'Mmrtextb.ttf',
        'Nirmala UI Semilight': 'Nirmalas.ttf',
        'Nirmala UI': 'Nirmala.ttf',
        'Nirmala UI Bold': 'Nirmalab.ttf',
        'Palatino Linotype': 'Pala.ttf',
        'Palatino Linotype Italic': 'Palai.ttf',
        'Palatino Linotype Bold': 'Palab.ttf',
        'Palatino Linotype Bold Italic': 'Palabi.ttf',
        'Segoe Print': 'Segoepr.ttf',
        'Segoe Print Bold': 'Segoeprb.ttf',
        'Segoe Script': 'Segoesc.ttf',
        'Segoe Script Bold': 'Segoescb.ttf',
        'Segoe UI Light': 'Segoeuil.ttf',
        'Segoe UI Light Italic': 'Seguili.ttf',
        'Segoe UI Semilight': 'Segoeuisl.ttf',
        'Segoe UI': 'Segoeui.ttf',
        'SimSun-ExtB': 'Simsunb.ttf',
        'Sylfaen': 'Sylfaen.ttf',
        'Symbol': 'Symbol.ttf',
        'Tahoma': 'Tahoma.ttf',
        'Tahoma Bold': 'Tahomabd.ttf',
        'Times New Roman': 'Times.ttf',
        'Times New Roman Italic': 'Timesi.ttf',
        'Times New Roman Bold': 'Timesbd.ttf',
        'Times New Roman Bold Italic': 'Timesbi.ttf',
        'Trebuchet MS': 'Trebuc.ttf',
        'Trebuchet MS Italic': 'Trebucit.ttf',
        'Trebuchet MS Bold': 'Trebucbd.ttf',
        'Trebuchet MS Bold Italic': 'Trebucbi.ttf',
        'Verdana': 'Verdana.ttf',
        'Verdana Italic': 'Verdanai.ttf',
        'Verdana Bold': 'Verdanab.ttf',
        'Verdana Bold Italic': 'Verdanaz.ttf',
        'Webdings': 'Webdings.ttf',
        'Wingdings': 'Wingding.ttf'}
